# Site settings
title: Jonas Rembser
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Personal homepage of Jonas Rembser.
#baseurl: "/example" # the subpath of your site, e.g. /blog/
url: "http://guitargeek.github.io" # the base hostname & protocol for your site
#twitter_username: guitargeek
github_username:  guitargeek

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
